from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer,
    Table, TableStyle, HRFlowable, KeepTogether,
    BaseDocTemplate, Frame, PageTemplate
)
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.units import mm
import datetime

# ─────────────────────────────────────────────
# COLORS
# ─────────────────────────────────────────────
DARK_BLUE   = colors.HexColor("#0D2B55")
ACCENT_BLUE = colors.HexColor("#2E86C1")
LIGHT_BLUE  = colors.HexColor("#EAF4FB")
RISK_RED    = colors.HexColor("#C0392B")
RISK_ORANGE = colors.HexColor("#E67E22")
RISK_GREEN  = colors.HexColor("#1E8449")
BORDER_GREY = colors.HexColor("#BDC3C7")
BG_GREY     = colors.HexColor("#F8F9FA")
TEXT_DARK   = colors.HexColor("#1A1A2E")
TEXT_GREY   = colors.HexColor("#5D6D7E")

PAGE_W, PAGE_H = A4
MARGIN    = 20 * mm
CONTENT_W = PAGE_W - 2 * MARGIN


# ─────────────────────────────────────────────
# HEADER / FOOTER DRAWN ON EVERY PAGE
# ─────────────────────────────────────────────
def draw_header_footer(c, doc):
    c.saveState()

    # Dark blue header bar
    c.setFillColor(DARK_BLUE)
    c.rect(0, PAGE_H - 28*mm, PAGE_W, 28*mm, fill=1, stroke=0)

    # Title
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 15)
    c.drawString(MARGIN, PAGE_H - 13*mm, "NeuroLens Clinical Monitoring Report")

    # Subtitle
    c.setFont("Helvetica", 8.5)
    c.setFillColor(colors.HexColor("#A9CCE3"))
    c.drawString(MARGIN, PAGE_H - 20*mm,
                 "AI-Assisted Mental Health Risk Assessment  |  Confidential")

    # Date + Report ID top-right
    c.setFillColor(colors.white)
    c.setFont("Helvetica", 8)
    date_str = datetime.datetime.now().strftime("%d %B %Y")
    rid = "NL-" + datetime.datetime.now().strftime("%Y%m%d%H%M")
    c.drawRightString(PAGE_W - MARGIN, PAGE_H - 13*mm, date_str)
    c.drawRightString(PAGE_W - MARGIN, PAGE_H - 20*mm, f"Report ID: {rid}")

    # Footer bar
    c.setFillColor(DARK_BLUE)
    c.rect(0, 0, PAGE_W, 12*mm, fill=1, stroke=0)
    c.setFillColor(colors.HexColor("#A9CCE3"))
    c.setFont("Helvetica", 7.5)
    c.drawString(MARGIN, 4*mm,
        "Generated by NeuroLens AI  |  For clinical monitoring only  "
        "|  Does not constitute medical diagnosis")
    c.drawRightString(PAGE_W - MARGIN, 4*mm, f"Page {doc.page}")

    c.restoreState()


# ─────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────
def get_risk_color(label):
    l = label.lower()
    if "high" in l:   return RISK_RED
    if "moderate" in l: return RISK_ORANGE
    return RISK_GREEN


def section_heading(title):
    return [
        Paragraph(
            f"<font color='#0D2B55'><b>{title}</b></font>",
            ParagraphStyle("SH", fontSize=12, leading=16,
                           spaceBefore=6, spaceAfter=2)
        ),
        HRFlowable(width="100%", thickness=1.5,
                   color=ACCENT_BLUE, spaceAfter=7)
    ]


def info_cell(label, value):
    return Paragraph(
        f"<font size='7.5' color='#5D6D7E'>{label}</font><br/>"
        f"<b>{value}</b>",
        ParagraphStyle("IC", fontSize=10, leading=14)
    )


# ─────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────
def generate_pdf_report(result, report,
                        filename="NeuroLens_Report.pdf"):

    doc = BaseDocTemplate(
        filename, pagesize=A4,
        leftMargin=MARGIN, rightMargin=MARGIN,
        topMargin=32*mm, bottomMargin=18*mm
    )

    frame = Frame(
        MARGIN, 18*mm,
        CONTENT_W, PAGE_H - 32*mm - 18*mm,
        id="main"
    )

    doc.addPageTemplates([
        PageTemplate(id="main", frames=[frame],
                     onPage=draw_header_footer)
    ])

    styles = getSampleStyleSheet()
    story  = []

    # ── PATIENT INFO BAR ─────────────────────
    story.append(Spacer(1, 3*mm))

    info_table = Table(
        [[
            info_cell("PATIENT",          "Anonymous / Test Subject"),
            info_cell("MONITORING WINDOW","30 Days"),
            info_cell("ASSESSMENT DATE",  datetime.datetime.now().strftime("%d %b %Y")),
            info_cell("CLINICIAN",        "NeuroLens AI"),
        ]],
        colWidths=[CONTENT_W / 4] * 4
    )
    info_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), BG_GREY),
        ('BOX',        (0,0), (-1,-1), 0.5, BORDER_GREY),
        ('LINEAFTER',  (0,0), (2,0),   0.5, BORDER_GREY),
        ('PADDING',    (0,0), (-1,-1), 10),
        ('VALIGN',     (0,0), (-1,-1), 'TOP'),
    ]))
    story.append(info_table)
    story.append(Spacer(1, 5*mm))

    # ── RISK SUMMARY ─────────────────────────
    story.extend(section_heading("Mental Health Risk Summary"))

    risk_color = get_risk_color(result["label"])

    badge = Table(
        [[Paragraph(
            f"<b>{result['label'].upper()}</b>",
            ParagraphStyle("Bdg", fontSize=12, textColor=colors.white,
                           alignment=TA_CENTER)
        )]],
        colWidths=[52*mm], rowHeights=[13*mm]
    )
    badge.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), risk_color),
        ('ALIGN',      (0,0), (-1,-1), 'CENTER'),
        ('VALIGN',     (0,0), (-1,-1), 'MIDDLE'),
    ]))

    score_para = Paragraph(
        f"<font size='26' color='#0D2B55'><b>{result['risk_score']:.2f}</b></font>"
        f"<font size='9' color='#5D6D7E'> / 1.00  Risk Score</font>",
        ParagraphStyle("Sc", alignment=TA_CENTER)
    )

    trend_para = Paragraph(
        "<font size='11' color='#E67E22'><b>+12% Elevated</b></font><br/>"
        "<font size='8' color='#5D6D7E'>vs. previous week</font>",
        ParagraphStyle("Tr", alignment=TA_CENTER)
    )

    risk_row = Table(
        [[badge, score_para, trend_para]],
        colWidths=[58*mm, 65*mm, CONTENT_W - 123*mm]
    )
    risk_row.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), LIGHT_BLUE),
        ('BOX',        (0,0), (-1,-1), 0.5, ACCENT_BLUE),
        ('LINEAFTER',  (0,0), (1,0),   0.5, BORDER_GREY),
        ('ALIGN',      (0,0), (-1,-1), 'CENTER'),
        ('VALIGN',     (0,0), (-1,-1), 'MIDDLE'),
        ('PADDING',    (0,0), (-1,-1), 12),
    ]))
    story.append(risk_row)
    story.append(Spacer(1, 5*mm))

    # ── CLINICAL SUMMARY ─────────────────────
    story.extend(section_heading("Clinical Summary"))

    summary = report.get("clinical_summary") or "No summary available."
    summary_box = Table(
        [[Paragraph(summary,
                    ParagraphStyle("SB", fontSize=10, leading=16,
                                   textColor=TEXT_DARK))]],
        colWidths=[CONTENT_W]
    )
    summary_box.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), BG_GREY),
        ('LINEBEFORE', (0,0), (0,-1), 3.5, ACCENT_BLUE),
        ('PADDING',    (0,0), (-1,-1), 12),
    ]))
    story.append(summary_box)
    story.append(Spacer(1, 5*mm))

    # ── KEY OBSERVATIONS ─────────────────────
    story.extend(section_heading("Key Observations"))

    obs_data = [
        ["Detected Signal",  "Status",      "Severity"],
        ["Voice Distress",   "Elevated",    "High"],
        ["Emotion Trend",    "Negative",    "Moderate"],
        ["Risk Progression", "Increasing",  "High"],
    ]

    obs_table = Table(
        obs_data,
        colWidths=[CONTENT_W*0.45, CONTENT_W*0.30, CONTENT_W*0.25]
    )
    obs_table.setStyle(TableStyle([
        ('BACKGROUND',     (0,0),  (-1,0),  DARK_BLUE),
        ('TEXTCOLOR',      (0,0),  (-1,0),  colors.white),
        ('FONTNAME',       (0,0),  (-1,0),  'Helvetica-Bold'),
        ('FONTSIZE',       (0,0),  (-1,-1), 10),
        ('ALIGN',          (0,0),  (-1,-1), 'LEFT'),
        ('VALIGN',         (0,0),  (-1,-1), 'MIDDLE'),
        ('GRID',           (0,0),  (-1,-1), 0.4, BORDER_GREY),
        ('PADDING',        (0,0),  (-1,-1), 10),
        ('ROWBACKGROUNDS', (0,1),  (-1,-1), [colors.white, BG_GREY]),
        # Color high severity cells
        ('BACKGROUND',     (2,1),  (2,1),   colors.HexColor("#FDEDEC")),
        ('BACKGROUND',     (2,3),  (2,3),   colors.HexColor("#FDEDEC")),
        ('BACKGROUND',     (2,2),  (2,2),   colors.HexColor("#FEF9E7")),
        ('TEXTCOLOR',      (1,1),  (1,1),   RISK_RED),
        ('TEXTCOLOR',      (1,2),  (1,2),   RISK_ORANGE),
        ('TEXTCOLOR',      (1,3),  (1,3),   RISK_RED),
        ('FONTNAME',       (1,1),  (-1,-1), 'Helvetica-Bold'),
    ]))
    story.append(obs_table)
    story.append(Spacer(1, 5*mm))

    # ── POTENTIAL CONCERNS ───────────────────
    concerns = report.get("concerns")
    if concerns:
        story.extend(section_heading("Potential Concerns"))
        c_box = Table(
            [[Paragraph(
                concerns,
                ParagraphStyle("CB", fontSize=10, leading=16,
                               textColor=colors.HexColor("#7B241C"))
            )]],
            colWidths=[CONTENT_W]
        )
        c_box.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#FDEDEC")),
            ('BOX',        (0,0), (-1,-1), 0.8, RISK_RED),
            ('LINEBEFORE', (0,0), (0,-1), 3.5, RISK_RED),
            ('PADDING',    (0,0), (-1,-1), 12),
        ]))
        story.append(c_box)
        story.append(Spacer(1, 5*mm))

    # ── SUGGESTED FOLLOW-UP ──────────────────
    story.extend(section_heading("Suggested Follow-Up"))

    followup = (report.get("follow_up") or "").strip() or \
        "Schedule a follow-up evaluation within one to two weeks."

    fu_box = Table(
        [[Paragraph(
            followup,
            ParagraphStyle("FU", fontSize=10, leading=16,
                           textColor=colors.HexColor("#1A5276"))
        )]],
        colWidths=[CONTENT_W]
    )
    fu_box.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#EBF5FB")),
        ('BOX',        (0,0), (-1,-1), 0.8, ACCENT_BLUE),
        ('LINEBEFORE', (0,0), (0,-1), 4,   ACCENT_BLUE),
        ('PADDING',    (0,0), (-1,-1), 12),
    ]))
    story.append(fu_box)
    story.append(Spacer(1, 7*mm))

    # ── SIGNATURE ROW ────────────────────────
    now_str = datetime.datetime.now().strftime("%d %b %Y, %H:%M")
    sig_table = Table(
        [[
            info_cell("REVIEWED BY",  f"NeuroLens AI System\n{now_str}"),
            info_cell("VERIFIED BY",  "Pending Clinician Review\n[Signature required]"),
        ]],
        colWidths=[CONTENT_W / 2] * 2
    )
    sig_table.setStyle(TableStyle([
        ('BOX',       (0,0), (-1,-1), 0.5, BORDER_GREY),
        ('LINEAFTER', (0,0), (0,-1),  0.5, BORDER_GREY),
        ('PADDING',   (0,0), (-1,-1), 12),
        ('BACKGROUND',(0,0), (-1,-1), BG_GREY),
    ]))
    story.append(sig_table)

    doc.build(story)
    print("Professional clinical report generated.")